name: 'Test'

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
  pull_request:

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 16, 17 ]

    steps:
      - uses: actions/checkout@v2

      - name: 'Setup Java ${{ matrix.java }}'
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: 'Cache Gradle'
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-jdk${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-jdk${{ matrix.java }}-gradle-

      - name: 'Test with Gradle'
        run: ./gradlew test --no-daemon --build-cache
